import coolWorldCover from './covers/coolworld.jpg';
import cureCover from './covers/cure.webp';
import mountEerieCover from './covers/Mount-Eerie-Night-Palace.webp';
import tylerCover from './covers/tyler.webp';
import utopiaCover from './covers/utopia.webp';

const albumData = [
  {
    id: 'utopia',
    name: 'Utopia',
    artist: 'Travis Scott',
    type: 'Album',
    releaseDate: '28 July 2023',
    recorded: '2019 - 2023',
    rating: 3.44,
    rated: 20229,
    ranked: '#253 for 2023',
    cover: utopiaCover.src,
    genres: [
      'Southern Hip Hop',
      'Experimental Hip Hop',
      'Trap',
      'Cloud Rap',
      'Alternative R&B',
      'Pop Rap',
      'Neo-Psychedelia',
    ],
    descriptors: [
      'psychedelic',
      'dark',
      'nocturnal',
      'progressive',
      'male vocalist',
      'drugs',
      'hedonistic',
      'atmospheric',
      'eclectic',
      'sexual',
      'sampling',
      'boastful',
      'surreal',
      'rhythmic',
      'alcohol',
      'vulgar',
      'futuristic',
      'party',
      'urban',
      'melodic',
    ],
    language: 'English',
    tracklist: [
      { name: 'Hyaena', duration: '3:42' },
      { name: 'Thank God', duration: '3:05' },
      { name: 'Modern Jam', duration: '4:15', feature: 'Teezo Touchdown' },
      { name: 'My Eyes', duration: '4:11' },
      { name: "God's Country", duration: '2:08' },
      { name: 'Sirens', duration: '3:24' },
      { name: 'Meltdown', duration: '4:06', feature: 'Drake' },
      { name: 'Fe!n', duration: '3:12', feature: 'Playboi Carti' },
      { name: 'Delresto (Echoes)', duration: '4:34', feature: 'Beyoncé' },
      { name: 'I Know ?', duration: '3:32' },
      { name: 'Topia Twins', duration: '3:43', feature: 'Rob49 & 21 Savage' },
      { name: 'Circus Maximus', duration: '4:19', feature: 'Swae Lee & The Weeknd' },
      { name: 'Parasail', duration: '3:01', feature: 'Yung Lean' },
      { name: 'Skitzo', duration: '4:15', feature: 'Young Thug' },
      { name: 'Lost Forever', duration: '4:03', feature: 'Westside Gunn & James Blake' },
      { name: 'Looove', duration: '3:58', feature: 'Kid Cudi' },
      { name: 'K-Pop', duration: '3:07', feature: 'Bad Bunny & The Weeknd' },
      { name: 'Telekinesis', duration: '5:04', feature: 'Future & SZA' },
      { name: 'Til Further Notice', duration: '3:32', feature: '21 Savage & James Blake' },
    ],
    review: {
      reviewer: 'silveira',
      stars: '★★★★☆',
      quote: 'BLM',
      content:
        'This is an album that I didn’t enjoy because he is bl...',
    },
    reviews: [
      {
        user: 'silveira',
        date: 'Aug 10, 2023',
        stars: 4,
        content:
          'This is an album that I didn’t enjoy when it was first released. I thought the beats were boring',
      },
    ],
  },
  {
    id: 'cure',
    name: 'Disintegration',
    artist: 'The Cure',
    cover: cureCover.src,
    rating: 4.5,
    rated: 50000,
    genres: ['Gothic Rock', 'Post-Punk'],
    descriptors: ['melancholic', 'atmospheric', 'introspective'],
    review: {
      reviewer: 'musicfan123',
      stars: '★★★★★',
      quote: 'A timeless masterpiece.',
      content:
        'Disintegration is one of the best albums of all time...',
    },
    reviews: [],
    tracklist: [
      { name: 'Plainsong', duration: '5:16' },
      { name: 'Pictures of You', duration: '7:28' },
      { name: 'Closedown', duration: '4:16' },
      { name: 'Lovesong', duration: '3:28' },
      { name: 'Last Dance', duration: '4:47' },
      { name: 'Lullaby', duration: '4:08' },
      { name: 'Fascination Street', duration: '5:16' },
      { name: 'Prayers for Rain', duration: '6:05' },
      { name: 'The Same Deep Water as You', duration: '9:19' },
      { name: 'Disintegration', duration: '8:18' },
      { name: 'Homesick', duration: '7:06' },
      { name: 'Untitled', duration: '6:30' },
    ],
    type: 'Album',
    releaseDate: 'May 2, 1989',
    recorded: '1988–1989',
    language: 'English',
    ranked: 'Ranked #543',
  },
  {
    id: 'tyler',
    name: 'Chromakopia',
    artist: 'Tyler, the Creator',
    releaseDate: '28 October 2024',
    rating: 3.67,
    rated: 19545,
    cover: tylerCover.src,
    genres: ['West Coast Hip Hop', 'Neo-Soul'],
    descriptors: ['groovy', 'catchy', 'energetic', 'playful'],
  },
  {
    id: 'mount-eerie',
    name: 'Night Palace',
    artist: 'Mount Eerie',
    releaseDate: '1 November 2024',
    rating: 3.99,
    rated: 6094,
    cover: mountEerieCover.src,
    genres: ['Slacker Rock', 'Avant-Folk', 'Post-Rock'],
    descriptors: ['moody', 'dreamy', 'atmospheric', 'reflective'],
  },
  {
    id: 'cool-world',
    name: 'Cool World',
    artist: 'Chat Pile',
    releaseDate: '11 October 2024',
    rating: 3.82,
    rated: 6330,
    cover: coolWorldCover.src,
    genres: ['Noise Rock', 'Sludge Metal'],
    descriptors: ['heavy', 'intense', 'chaotic', 'raw'],
  },
];

export default albumData;
